name: Github Pages Deployment

on:
  push: 
    branches:
      - "main"

jobs: 
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm install

      - name: Build & Deployment
        run: npm run deploy
