name: Github Pages Deployment

on:
  push: 
    branches:
      - "main"

jobs: 
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install & Build
        run: npm install && npm run build

      - name: Deploy
        uses: bettaibi/chatup@v1
        with: 
          branch: gh-pages
          folder: build